# ``conda env create --file environment.yml``
# or
# ``conda env create --name <myEnvName> --file environment.yml``

name: aplc-optimization
channels:
  - defaults
  - conda-forge
  - http://conda.anaconda.org/gurobi
dependencies:
  - astropy
  - gurobi
  - imageio
  - jupyter
  - matplotlib
  - memory_profiler
  - numpy
  - pandas
  - pip
  - pytest
  - python>=3.7
  - scipy
  - time
  - pip:
    - asdf
    - hcipy
    - pytest

